language: elixir
otp_release:
  - 22.2
elixir:
  - 1.10.0
before_script:
  - export SCRIVENER_ECTO_DB_USER=postgres
  - MIX_ENV=test mix db.reset
script:
  - mix test
  - mix format --check-formatted
